// Copyright 2023 - YetiTech Studios, Pvt Ltd. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

// Generic tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(InvalidTag);

// Device tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(PCDeviceTag);

// Operating System tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(UnixOsTag);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(NonUnixOsTag);

// Hardware tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(MbbTag);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(CpuTag);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(GpuTag);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(HddTag);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(PsuTag);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(RamTag);

// CPU socket tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LGA1150_Tag);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LGA1151_Tag);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LGA1155_Tag);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LGA2011_Tag);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LGA2066_Tag);

// Directory tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(DirRoot_Tag);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(DirUsers_Tag);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(DirDesktop_Tag);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(DirDocuments_Tag);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(DirDownloads_Tag);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(DirHome_Tag);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(DirMusic_Tag);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(DirPictures_Tag);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(DirVideos_Tag);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(DirOther_Tag);

// Widget tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(OSWidget_Installation_Tag);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(OSWidget_Loading_Tag);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(OSWidget_InitialStartup_Tag);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(OSWidget_InitialStartupFinish_Tag);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(OSWidget_Logon_Tag);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(OSWidget_Desktop_Tag);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(OSWidget_Shutdown_Tag);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(OSWidget_Restart_Tag);
